{
 "title": "Dashboard Candidatos",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total de Candidatos",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS total FROM public.candidatos;"
    }
   ]
  },
  {
   "title": "Candidatos por Estado Civil",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT estado_civil, COUNT(*) AS quantidade FROM public.candidatos GROUP BY estado_civil ORDER BY quantidade DESC;"
    }
   ]
  },
  {
   "title": "Distribuição por Sexo (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT sexo, COUNT(*) AS quantidade, ROUND((COUNT(*) * 100.0 / (SELECT COUNT(*) FROM public.candidatos)), 2) AS percentual FROM public.candidatos GROUP BY sexo ORDER BY sexo;"
    }
   ]
  },
  {
   "title": "Faixa Etária dos Candidatos",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT FLOOR(DATE_PART('year', AGE(data_nascimento)) / 10) AS faixa_inicial, CONCAT(FLOOR(DATE_PART('year', AGE(data_nascimento)) / 10) * 10, ' - ', FLOOR(DATE_PART('year', AGE(data_nascimento)) / 10) * 10 + 9) AS faixa_idade, COUNT(*) AS quantidade FROM public.candidatos GROUP BY faixa_inicial ORDER BY faixa_inicial;"
    }
   ]
  },
  {
   "title": "Candidatos cadastrados por dia",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT DATE(criado_em) AS time, COUNT(*) AS quantidade FROM public.candidatos GROUP BY time ORDER BY time;"
    }
   ]
  }
 ]
}